---
title: "GP Deprivation Dashboard"
author: "GirlThatGraphs"
output: 
  flexdashboard::flex_dashboard:
  orientation: rows
social: menu
source_code: embed
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard

library(flexdashboard)

# SETUP
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(shiny)
library(scales)
library(htmltools)
library(rvest)
library(dplyr)
library(xml2)
library(tidyr)
library(IMD)
library(viridis)


  #Specifying the url for desired website to be scraped
  url <- paste("https://digital.nhs.uk/data-and-information/publications/statistical/patients-registered-at-a-gp-practice")

#Reading the HTML code from the website
webpage <- read_html(url)

#Using CSS selectors to scrape the rankings section
web_data_html <- html_nodes(webpage,'.cta__button')

#Converting the ranking data to text
web_data <- html_text(web_data_html)%>% 
  gsub("Patients Registered at a GP Practice, ", "", .) %>% 
  gsub("Patients Registered at a GP Practice - ", "", .)
  
  web_data_short <-  data.frame(web_data) %>% 
  filter(grepl('April|July|October|January', web_data),
         !grepl('\n', web_data)) %>% 
    head(1) %>% 
    pull() %>% 
    gsub(" ", "-", .) %>% 
    tolower()


  
#Specifying the url for desired website to be scraped
url2 <- paste(url,web_data_short, sep = "/")

#Reading the HTML code from the website
webpage2 <- read_html(url2)

#Using CSS selectors to scrape the rankings section
web_data_html2 <- html_nodes(webpage2,'.nhsd-a-box-link')[8] 

web_data2 <- xml_attrs(web_data_html2[[1]]) %>% 
  data.frame() %>% 
  head(1) %>% 
  pull()


temp <- tempfile()
download.file(web_data2,temp)
data1 <- unz(temp, "gp-reg-pat-prac-lsoa-all.csv")
data <- read.csv(data1,
                   header = TRUE)
unlink(temp)

data <- data %>% filter(PRACTICE_CODE %in% c("L85055","L85020","L85601","L85016","L85066","L85018","L85011","L85007","L85624","L85021","L85025","L85609","L85004","L85006","L85022","L85065","L85035","L85030","L85003","L85001","L85008","L85047","L85053","L85026","L85010","L85033","L85038","L85050","L85062","L85031","L85040","L85019","L85037","L85056","L85611","L85064","L85043","L85017","L85024","L85015","L85013","L85036","L85044","L85051","L85048","L85607","L85028","L85023","L85054","L85042","L85014","L85619","L85032","L85039","L85061","L85046","L85612","L85029","L85052","L85012","L85034","L85002","Y01163","L85009","L85027"
))  %>% left_join(IMD::imd_england_lsoa, by = c("LSOA_CODE" = "lsoa_code")) %>% 
  select(EXTRACT_DATE, PRACTICE_CODE, PRACTICE_NAME, NUMBER_OF_PATIENTS, IMD_decile) %>% 
  group_by(EXTRACT_DATE, PRACTICE_CODE, PRACTICE_NAME, IMD_decile) %>% 
  summarize(NUMBER_OF_PATIENTS = sum(NUMBER_OF_PATIENTS)) %>% 
  ungroup() %>% 
  drop_na()



```

Inputs {.sidebar}
-----------------------------------------------------------------------
  

```{r Practice, echo = FALSE, message = FALSE, warning = FALSE}
selectizeInput("Practice", label = "GP_Practice",
            choices=data$PRACTICE_NAME)
```


```{R data prep, include=FALSE}

PracticeIn <- reactive((input$Practice))

```



```{R myfunction, include=FALSE}


create_table <- 
  function (Practice) {
    
        datafilter <- data %>% filter(PRACTICE_NAME == Practice)
  }

```


Row
-----------------------------------------------------------------------
  
```{r Table, echo = FALSE, message = FALSE, warning = FALSE}
  
table <- reactive({create_table(Practice=PracticeIn())})


```
  
``` {r Graph, echo = FALSE, message = FALSE, warning = FALSE}


  
renderPlot({ggplot(data = table(),
       aes(x = factor(`IMD_decile`,
                      level = c('1',
                                '2',
                                '3',
                                '4',
                                '5',
                                '6',
                                '7',
                                '8',
                                '9',
                                '10')),
           y = `NUMBER_OF_PATIENTS`)) +

   geom_bar(stat = "identity",
           aes(fill = factor(`IMD_decile`))) +
    scale_fill_viridis(limits = c(1,2,3,4,5,6,7,8,9,10),
                       discrete = TRUE,
                     direction = -1) +
  scale_x_discrete(limits = c('1',
                              '2',
                              '3',
                              '4',
                              '5',
                              '6',
                              '7',
                              '8',
                              '9',
                              '10')) +
  expand_limits(y = 0) +
  scale_y_continuous(expand = c(0,
                                0),
                     labels = comma) +
  labs(
    title = paste("Total GP-Registered Population by Index of Multiple Deprivation Decile"),
    caption = paste("Data source: NHSE"),
       subtitle = paste("1 = Most Deprived, 10 = Least Deprived"))+
    theme(plot.title = element_text(family = "Calibri",
size = 18,
margin = margin(12,
0,
4,
0),
color = "#231f20",
face = "bold",
hjust = 0),
plot.title.position = "plot",
plot.subtitle = element_text(family = "Calibri",
size = 12,
margin = margin(4,
0,
12,
0),
colour = "#231f20"),
plot.caption = element_text(family = "Calibri",
size = 10,
color = "#768692",
margin = margin(4,
0,
8,
0),
hjust = 0),
plot.caption.position = "plot",
plot.background = element_rect(fill = "#FFFFFF"),
legend.position = "top",
legend.text.align = 0,
legend.background = element_blank(),
legend.title = element_blank(),
legend.key = element_blank(),
legend.text = element_text(family = "Calibri",
size = 12,
color = "#231f20"),
legend.justification = 'left',
legend.margin = margin(-0.2,
0,
0.2,
-1.91,
"cm"),
axis.title = element_blank(),
axis.title.x = element_blank(),
axis.title.y = element_blank(),
axis.text = element_text(family = "Calibri",
size = 12,
color = "#231f20"),
axis.text.x = element_text(margin = margin(5,
0,
10,
0)),
axis.text.y = element_text(margin = margin(0,
5,
0,
0)),
axis.ticks.x = element_line(colour = "#231f20",
size = 0.5),
axis.ticks.length = unit(0.25,
"cm"),
axis.ticks.y = element_blank(),
axis.line = element_blank(),
axis.line.x = element_line(color = "#231f20",
size = 0.5),
panel.grid.minor = element_blank(),
panel.grid.major.y = element_line(color = "#E8EDEE",
size = 0.25),
panel.grid.major.x = element_blank(),
panel.background = element_rect(fill = "#FFFFFF",
colour = "#FFFFFF",
size = 0.5,
linetype = "solid"),
strip.background = element_rect(fill = "#FFFFFF"),
strip.text = element_text(size = 10,
hjust = 0),
plot.margin = unit(c(0,
0.4,
0,
0.4),
"cm"))
})

  

```


```{r Table2, echo = FALSE, message = FALSE, warning = FALSE}
  

renderTable({table() })


```

